[package]
name = "riftri-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[[bin]]
name = "riftri"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
riftri-core = { path = "../riftri-core" }
riftri-storage = { path = "../riftri-storage" }
serde_json.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true

[dev-dependencies]
tempfile.workspace = true
