# Generated by package/scripts/update-homebrew-formula.mjs. Do not edit by hand.
class Riftri < Formula
  desc "Lightweight Git workspaces for parallel development"
  homepage "https://riftri.dev"
  version "0.2.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.2.3/riftri-darwin-arm64-v0.2.3.tar.gz"
      sha256 "325e0b2255d50fa4ba0995a0e733f18dd9a4a4587712dcb22e22515f8eae5b28"
    end
    on_intel do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.2.3/riftri-darwin-x64-v0.2.3.tar.gz"
      sha256 "d5a973aa9198ee606fe4dcc814bd440462a549b471aa3f3080ecd9eb430fcbf9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.2.3/riftri-linux-arm64-gnu-v0.2.3.tar.gz"
      sha256 "91aafe58108dfaebc3ca22f2342413d1e5dcb06c3aac7c6759607f7d651cad11"
    end
    on_intel do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.2.3/riftri-linux-x64-gnu-v0.2.3.tar.gz"
      sha256 "c575224cffcfacfbd9f155c06560916a3abb32d70a0d44d9b54c0fc8b9f692f2"
    end
  end

  def install
    bin.install "riftri"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/riftri --version")
    system "git", "init", "--quiet", testpath/"repository"
    report = shell_output("#{bin}/riftri doctor #{testpath}/repository --json")
    assert_match "storage_capabilities", report
  end
end
