# Generated by package/scripts/update-homebrew-formula.mjs. Do not edit by hand.
class Riftri < Formula
  desc "Lightweight Git workspaces for parallel development"
  homepage "https://riftri.dev"
  version "0.3.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.3.5/riftri-darwin-arm64-v0.3.5.tar.gz"
      sha256 "41fd6f799ffdcc9beb6b6edeccc91dc81ed0162f3213e1371809f626e350119c"
    end
    on_intel do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.3.5/riftri-darwin-x64-v0.3.5.tar.gz"
      sha256 "e17efd032f2e83d2f5618288287a5b45155a0e5c3925ea5c632da55f5f497f36"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.3.5/riftri-linux-arm64-gnu-v0.3.5.tar.gz"
      sha256 "25597295a76e2262aed1af0afe62d3d6d4af22e7268cd804f29fee167fabe1ac"
    end
    on_intel do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.3.5/riftri-linux-x64-gnu-v0.3.5.tar.gz"
      sha256 "1fa96dc8935d056b92a7116e3260cff5956e1aa0121221d8691596daed184154"
    end
  end

  def install
    bin.install "riftri"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/riftri --version")
    system "git", "init", "--quiet", testpath/"repository"
    report = shell_output("#{bin}/riftri doctor #{testpath}/repository --json")
    assert_match "storage_capabilities", report
  end
end
