# Generated by package/scripts/update-homebrew-formula.mjs. Do not edit by hand.
class Riftri < Formula
  desc "Lightweight Git workspaces for parallel development"
  homepage "https://riftri.dev"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.3.0/riftri-darwin-arm64-v0.3.0.tar.gz"
      sha256 "a62f945bb3e2693610762bd10a46c623caf3f42411a5f0396545681057358a43"
    end
    on_intel do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.3.0/riftri-darwin-x64-v0.3.0.tar.gz"
      sha256 "b9bb67d66037a631a4c9059f0f438975592942ed12f304d590cc4bf753cee477"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.3.0/riftri-linux-arm64-gnu-v0.3.0.tar.gz"
      sha256 "805fbcb8c219697245c320bd9aaf0bfd106faebdc6fd082ffd13a6c9c765d873"
    end
    on_intel do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.3.0/riftri-linux-x64-gnu-v0.3.0.tar.gz"
      sha256 "ebcab7d055e634e76dbec1f584435db79c45dc7db02d4d3ba6aee8f7c8174d7f"
    end
  end

  def install
    bin.install "riftri"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/riftri --version")
    system "git", "init", "--quiet", testpath/"repository"
    report = shell_output("#{bin}/riftri doctor #{testpath}/repository --json")
    assert_match "storage_capabilities", report
  end
end
