# Generated by package/scripts/update-homebrew-formula.mjs. Do not edit by hand.
class Riftri < Formula
  desc "Lightweight Git workspaces for parallel development"
  homepage "https://riftri.dev"
  version "0.6.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.6.1/riftri-darwin-arm64-v0.6.1.tar.gz"
      sha256 "074226312d838d3f5f2b80aa7369f4a9efeea5b478c2ccd69f60e5ac86f351c7"
    end
    on_intel do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.6.1/riftri-darwin-x64-v0.6.1.tar.gz"
      sha256 "f0c399447bc518dbaad1f8f9e1b74326f25ee06d4893299361ed87b3218d2b52"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.6.1/riftri-linux-arm64-gnu-v0.6.1.tar.gz"
      sha256 "bb3ea2a7fbdb78586ab0a069b41c0640d6cd4062baf5e975afe71024246b4618"
    end
    on_intel do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.6.1/riftri-linux-x64-gnu-v0.6.1.tar.gz"
      sha256 "c0e7a27981e3bf36e1180f4d81b69cdd2ac46105ea0609c9163d981ff91f0882"
    end
  end

  def install
    bin.install "riftri"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/riftri --version")
    system "git", "init", "--quiet", testpath/"repository"
    report = shell_output("#{bin}/riftri doctor #{testpath}/repository --json")
    assert_match "storage_capabilities", report
  end
end
