# Generated by package/scripts/update-homebrew-formula.mjs. Do not edit by hand.
class Riftri < Formula
  desc "Lightweight Git workspaces for parallel development"
  homepage "https://riftri.dev"
  version "0.6.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.6.3/riftri-darwin-arm64-v0.6.3.tar.gz"
      sha256 "0b90d27872d99bc19b6711c05b13fd0b4450776734bd455bc9f6775a970b508b"
    end
    on_intel do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.6.3/riftri-darwin-x64-v0.6.3.tar.gz"
      sha256 "dd583aec090df80e032eecee012cbe411b7d123ed2d08d81951436446fa50e67"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.6.3/riftri-linux-arm64-gnu-v0.6.3.tar.gz"
      sha256 "d4ea9634ab76b0c8365644f2f5ddc76f8573873a8f4fee550a3bb434376b5ca2"
    end
    on_intel do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.6.3/riftri-linux-x64-gnu-v0.6.3.tar.gz"
      sha256 "a85aba3d81e73f6caa671f67a8f8c543e945a52cbcf6ba9114b1d231ce96106d"
    end
  end

  def install
    bin.install "riftri"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/riftri --version")
    system "git", "init", "--quiet", testpath/"repository"
    report = shell_output("#{bin}/riftri doctor #{testpath}/repository --json")
    assert_match "storage_capabilities", report
  end
end
