# Generated by package/scripts/update-homebrew-formula.mjs. Do not edit by hand.
class Riftri < Formula
  desc "Lightweight Git workspaces for parallel development"
  homepage "https://riftri.dev"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.5.0/riftri-darwin-arm64-v0.5.0.tar.gz"
      sha256 "94574b595c483bbf0af0b083874df07295924bf1fc7e3a138d077127c2c21934"
    end
    on_intel do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.5.0/riftri-darwin-x64-v0.5.0.tar.gz"
      sha256 "5ca3227089ba0852db4cd57e8bbec320514fda22393c086a435fa76e4cfd4f25"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.5.0/riftri-linux-arm64-gnu-v0.5.0.tar.gz"
      sha256 "65c6445ccc3b430299101742a3f71e012c1818f1c45322fc636c109648e691fe"
    end
    on_intel do
      url "https://github.com/assistant-ui/riftri/releases/download/v0.5.0/riftri-linux-x64-gnu-v0.5.0.tar.gz"
      sha256 "22e6f27543b719c531f376ffaf3dd314162e96150db8a5f835ae21df1e655478"
    end
  end

  def install
    bin.install "riftri"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/riftri --version")
    system "git", "init", "--quiet", testpath/"repository"
    report = shell_output("#{bin}/riftri doctor #{testpath}/repository --json")
    assert_match "storage_capabilities", report
  end
end
