[package]
name = "riftri-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[features]
default = []
native-cow-integration = []

[dependencies]
fs2.workspace = true
riftri-git = { path = "../riftri-git" }
riftri-storage = { path = "../riftri-storage" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
